stages:
  - build
  - test

build:
  stage: build
  image: maciekbaron/sgdk:latest
  script:
    - make -f $GENDEV/sgdk/mkfiles/makefile.gen clean all
  artifacts:
    paths:
      - out/
  only:
    refs:
      - master
      - merge_requests

test:
  stage: test
  image: maciekbaron/retroarch:latest
  artifacts:
    paths:
      - screenshot.png
  script:
    - Xvfb :1 -screen 0 1024x768x24 </dev/null &
    - export DISPLAY=":1"
    - sleep 3
    - /usr/bin/retroarch -L /usr/lib/x86_64-linux-gnu/libretro/genesis_plus_gx_libretro.so "out/rom.bin" &
    - sleep 10
    - import -display $DISPLAY -window root screenshot.png
  only:
    refs:
      - master
      - merge_requests
